### ISSUE TITLE
Fails with alpine node:12 images

### ISSUE THREAD

**Issue by abdullateef97** [mserranom/bbrun#58]
using node:12-alpine as my base image 
after running `bbrun --pipeline branches:development` I get the following error
`
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/ws/bash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`

**Comment by migueldiogo-cycleon** [comment]
I have the same issue on another image based on alpine, `rastasheep/alpine-node-chromium:10-alpine`.
Perhaps because it doesn't have `bash` installed?
